package com.nativeslang.sql;

public class Generated extends ColumnType {
	private final ColumnType core;

	public Generated(ColumnType core) {
		this.core = core;
	}

	@Override
	public String compile() {
		return core.compile() + " generated by default as identity";
	}
}
